import {
  Award,
  BarChart3,
  BookOpen,
  Briefcase,
  CalendarClock,
  ClipboardCheck,
  CreditCard,
  FileText,
  Funnel,
  Globe,
  GraduationCap,
  IndianRupee,
  Layers,
  Lock,
  MessageCircle,
  MonitorPlay,
  Palette,
  Radio,
  Receipt,
  Repeat2,
  ScanText,
  School,
  Target,
  TrendingUp,
  UserCog,
  Users,
  Video,
  type LucideIcon,
} from "lucide-react";

// Icons are passed around by name so page data stays serialisable (it crosses
// the server → client boundary) and the set stays small.
export const SOLUTION_ICONS = {
  award: Award,
  chart: BarChart3,
  book: BookOpen,
  briefcase: Briefcase,
  clock: CalendarClock,
  tests: ClipboardCheck,
  card: CreditCard,
  file: FileText,
  funnel: Funnel,
  globe: Globe,
  graduation: GraduationCap,
  rupee: IndianRupee,
  layers: Layers,
  lock: Lock,
  chat: MessageCircle,
  play: MonitorPlay,
  palette: Palette,
  live: Radio,
  receipt: Receipt,
  repeat: Repeat2,
  scan: ScanText,
  school: School,
  target: Target,
  trend: TrendingUp,
  roles: UserCog,
  users: Users,
  video: Video,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof SOLUTION_ICONS;
