import {
  Award,
  BadgeCheck,
  BookOpenCheck,
  Briefcase,
  Building2,
  CalendarCheck,
  CircleHelp,
  ClipboardCheck,
  Funnel,
  Globe,
  House,
  IndianRupee,
  Info,
  Layers,
  Mail,
  MonitorPlay,
  Newspaper,
  Palette,
  ScanText,
  School,
  Scale,
  ShieldCheck,
  Target,
  type LucideIcon,
} from "lucide-react";
import type { IconKey } from "@/lib/site/pages";

// Page icons for menus and cards. AI is a document being read, never a sparkle.
export const ICONS: Record<IconKey, LucideIcon> = {
  home: House,
  platform: Layers,
  courses: MonitorPlay,
  exams: ClipboardCheck,
  ai: ScanText,
  crm: Funnel,
  brand: Palette,
  coaching: Building2,
  testPrep: Target,
  online: Globe,
  training: Briefcase,
  school: School,
  about: Info,
  why: BadgeCheck,
  pricing: IndianRupee,
  demo: CalendarCheck,
  contact: Mail,
  faq: CircleHelp,
  blog: Newspaper,
  guide: BookOpenCheck,
  compare: Scale,
  best: Award,
  legal: ShieldCheck,
};
